import Head from "next/head";
import { Text } from "@chakra-ui/react";
import { PContainer } from "@/components/PContainer";
import {
  Display,
  Label,
  Paragraph,
  Subtitle,
  Title,
} from "@/components/Typography";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
